import { z } from "zod";
import { optionalHttpUrl, optionalText, requiredEmail, requiredPhone, requiredText } from "./shared";

/**
 * Public "Join as a Creator" form. Mirrors propertySubmissionSchema's
 * philosophy — minimal, no proof required up front, only ever creates a
 * PENDING InfluencerSubmission row (see actions.ts).
 */
export const influencerSubmissionSchema = z.object({
  name: requiredText("Name").pipe(z.string().max(120, "Name must be 120 characters or fewer")),
  category: optionalText,
  bio: optionalText,
  instagramUrl: optionalHttpUrl,
  youtubeUrl: optionalHttpUrl,
  websiteUrl: optionalHttpUrl,
  photoUrl: optionalHttpUrl,
  contactName: requiredText("Your name"),
  contactEmail: requiredEmail,
  contactPhone: requiredPhone,
  // A real visitor never sees or fills this — see JoinAsInfluencerForm.tsx.
  honeypot: optionalText,
});

export type InfluencerSubmissionInput = z.infer<typeof influencerSubmissionSchema>;

/**
 * Pure transform from validated form input + server-resolved context (any
 * detected duplicate) to the InfluencerSubmission create payload.
 * influencerId/slug/status are never part of this — a submission never
 * touches the public Influencer table by itself.
 */
export function buildInfluencerSubmissionCreateData(
  input: InfluencerSubmissionInput,
  context: { duplicateOfInfluencerId: string | null }
) {
  return {
    name: input.name,
    category: input.category,
    bio: input.bio,
    instagramUrl: input.instagramUrl,
    youtubeUrl: input.youtubeUrl,
    websiteUrl: input.websiteUrl,
    photoUrl: input.photoUrl,
    contactName: input.contactName,
    contactEmail: input.contactEmail,
    contactPhone: input.contactPhone,
    duplicateOfInfluencerId: context.duplicateOfInfluencerId,
  };
}

/** Trims/lowercases/collapses whitespace so obviously-the-same names are recognized as a match. */
export function normalizeNameForDuplicateMatch(name: string): string {
  return name.trim().toLowerCase().replace(/\s+/g, " ");
}

export interface InfluencerDuplicateCandidate {
  id: string;
  name: string;
}

/** An "obvious" duplicate only — an exact name match (after normalization). Never fuzzy/approximate, never auto-rejects. */
export function findObviousInfluencerDuplicate(
  submission: { name: string },
  candidates: InfluencerDuplicateCandidate[]
): InfluencerDuplicateCandidate | null {
  const normalizedSubmission = normalizeNameForDuplicateMatch(submission.name);
  return candidates.find((candidate) => normalizeNameForDuplicateMatch(candidate.name) === normalizedSubmission) ?? null;
}

export interface ApprovedInfluencerSubmissionLike {
  name: string;
  category: string | null;
  bio: string | null;
  instagramUrl: string | null;
  youtubeUrl: string | null;
  websiteUrl: string | null;
  photoUrl: string | null;
  contactName: string;
  contactEmail: string;
  contactPhone: string;
}

/**
 * Pure — maps an approved submission's fields to an Influencer create
 * payload. status is PUBLISHED and claimed is true (the submitter IS the
 * creator, submitting their own real profile — the same trust bar an
 * approved claim already clears); featured/order/ratings stay untouched
 * defaults — those remain a separate, later, explicit admin decision.
 * `slug` is generated by the caller since it depends on which slugs
 * already exist.
 */
export function buildInfluencerCreateDataFromSubmission(submission: ApprovedInfluencerSubmissionLike, slug: string) {
  return {
    slug,
    name: submission.name,
    category: submission.category,
    bio: submission.bio,
    instagramUrl: submission.instagramUrl,
    youtubeUrl: submission.youtubeUrl,
    websiteUrl: submission.websiteUrl,
    photoUrl: submission.photoUrl,
    contactEmail: submission.contactEmail,
    contactPhone: submission.contactPhone,
    status: "PUBLISHED" as const,
    claimed: true as const,
  };
}

/** Pure — the InfluencerClaimRequest created alongside an approved submission, so the submitter gets the exact same owner-access mechanism a claimed profile's owner would. */
export function buildInfluencerClaimRequestDataFromSubmission(
  submission: { contactName: string; contactEmail: string; contactPhone: string },
  params: { influencerId: string; adminId: string; now: Date }
) {
  return {
    influencerId: params.influencerId,
    claimantName: submission.contactName,
    email: submission.contactEmail,
    phone: submission.contactPhone,
    status: "APPROVED" as const,
    reviewedAt: params.now,
    reviewedById: params.adminId,
  };
}
